// src3/urgentcarebumperrepair/src/app/bumperrepair/bumperrepair.component.ts
import { Component, OnInit, Input } from '@angular/core';
import {CommonModule} from '@angular/common';


@Component({
  selector: 'app-bumperrepair',
  templateUrl: './bumperrepair.component.html',
  styleUrls: ['./bumperrepair.component.css']
})
export class BumperrepairComponent implements OnInit {

  constructor() { }

  public config = {
    effect: 'coverflow',
    slidesPerView: 'auto',
    init: true,
    loop: true,
    coverflowEffect: {
      rotate: 100,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows: false,

    },
    pagination: {
      el: '.swiper-pagination',
      dynamicBullets: true,
    },
    autoplay: {
      delay: 5000,
      disableOnInteraction: true,
    },
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },

};

  // tslint:disable-next-line: typedef
  toHeader(){
    document.getElementById('header').scrollIntoView();
  }

  ngOnInit() {
  }

}

<main>
  <!-- Landing Area -->
  <div class="captionBumperRepairHeader mt-5" style="background-color:rgb(0,0,0)">
    <div class="bumper-landing-text">
      <div class="bumper-landing-text-inner">
        <h1 class="title">Bumper Repair</h1>
        <h6 class="text-white">Not all plastic bumpers need to be replaced; they can often be repaired to factory finish in our cost-efficient, quick and durable process.</h6>
    <p></p>
    <h6 class="text-white">
    Urgent Care Bumper Repair’s expertise is in restoring your damaged bumper to as it was new.
    If necessary, we can replace your parts whether they require paint to match the vehicle or a part that does not require any paint.
    If your new part does require paint, we have the ability to collect a color sample and color code along with the deposit for the part.
    Once painted, we will bring it to you or you can come to us for installation which takes one to two hours.
    Which gives you the ability to use your vehile while the part is being painted. No need to leave your vehicle at a shop for any reason (NO RENTAL CAR NEEDED).
    <!--  Urgent Care Bumper Repair’s expertise is in restoring your damaged bumper to as it was new.
        If your part does need to be replaced, I can bring it to you and assemble it, painted!
      Utilizing a state-of-the-art computerized color matching system;
      using only the highest quality paint (PPG Global) and products (3M and Sata) and applying nine years of knowledge and craftsmanship;
      your repair will be seamless and undetectable.
      It doesn’t matter if it’s scratched, scuffed, punctured, peeling, cracked, dented, you-name-it;
      you will get the best repair that you will be able to find out there. -->
    </h6>
    <p></p>
    <h6 class="text-white">
    <!--  Your satisfaction is most important and any painted part is backed by our warranty for as long as you own the car!
      Save a ton of time, avoid the headache of being without your car and spend HALF the amount of most body shops!
      Give me a call to restore your car today, right in your driveway! -->
    </h6>

    <a (click) ="toHeader()" class="btn" id="view-work">
          View Our Gallery
        </a>
      </div>
    </div>

  </div>

  <div class="images" id="bumperrepair">
    <div id="header">
      <h2>Our Work</h2>
    </div>


    <div class="caption">
   <div class="swiper-container" [swiper] = "config">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="assets/images/M4/069.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/070.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/071.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/072.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/073.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/074.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/075.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/076.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/077.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/078.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/079.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/080.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/M4/081.jpg"  class="captionImages" alt="..."></div>


    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination M4-pagination swiper-pagination-white"></div>
    <div class="swiper-button-prev M4-swiper-button-prev swipeColor"></div>
    <div class="swiper-button-next M4-swiper-button-next swipeColor"></div>
  </div>
  </div>

  <div class="caption1">
      <img class="categoryLogo" src="assets/images/logo2.png"/>
    </div>

    <div class="caption">
    <div class="swiper-container" [swiper] = "config">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="assets/images/Car1/082.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/083.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/084.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/085.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/086.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/087.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/088.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/091.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/092.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/093.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/094.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/095.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/096.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/097.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Car1/098.jpg"  class="captionImages" alt="..."></div>

    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination car1-pagination swiper-pagination-white"></div>
    <div class="swiper-button-prev car1-swiper-button-prev swipeColor"></div>
    <div class="swiper-button-next car1-swiper-button-next  swipeColor"></div>
    </div>
  </div>

  <div class="caption1">
      <img class="categoryLogo" src="assets/images/logo2.png"/>
    </div>

    <div class="caption" >
    <div class="swiper-container" [swiper] = "config">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_1.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_2.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_3.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_4.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_5.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_6.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_7.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_8.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_9.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_10.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_11.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_12.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_13.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_14.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_15.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_16.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_17.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_18.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_19.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_20.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_21.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_22.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_23.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_24.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_25.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_26.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_27.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_28.jpg"   class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/Aptera/IMG_29.jpg"   class="captionImages" alt="..."></div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination aptera-pagination swiper-pagination-white"></div>
    <div class="swiper-button-prev aptera-swiper-button-prev swipeColor"></div>
    <div class="swiper-button-next aptera-swiper-button-next swipeColor"></div>
        </div>
  </div>

  <div class="caption1">
    <img class="categoryLogo" src="assets/images/logo2.png"/>
  </div>

    <div class="caption" >
    <div class="swiper-container" [swiper] = "config">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="assets/images/porsche/150.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/porsche/151.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/porsche/152.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/porsche/153.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/porsche/154.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/porsche/155.jpg"  class="captionImages" alt="..."></div>
      <div class="swiper-slide"><img src="assets/images/porsche/156.jpg"  class="captionImages" alt="..."></div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination swiper-pagination-white"></div>
    <div class="swiper-button-prev porsche-swiper-button-prev swipeColor"></div>
    <div class="swiper-button-next porsche-swiper-button-next swipeColor"></div>
    </div>
  </div>

    <div class="captionBottom">
      <div class="theButton">
    <a [routerLink]="['/service']" routerLinkActive="router-link-active" class="btn" id="view-work">
      Return To Services
    </a>
  </div>
    </div>
  </div>
</main>

// src/features/bumperrepair/Bumperrepair.tsx
import { Box, Button, Grid, Link, Stack, Typography } from "@mui/material";
import { NavLink } from "react-router-dom";
import { Swiper, SwiperSlide } from "swiper/react";
import { EffectCoverflow, Pagination, Navigation } from "swiper";
import './Bumperrepair.css';
export default function Bumperrepair() {
  const scrollToView = () => {
    const serviceRef = document.getElementById('serviceRef');
    if (serviceRef) {
      serviceRef.scrollIntoView({ behavior: 'smooth' });
    }
  };
  return (
    <>

      <Stack className="services" sx={{ display: { xs: 'flex', sm: 'flex', md: 'flex' } }}>

        <Stack sx={{ p: 0, textAlign: 'center' }}>
          <Grid className="captionBumperrepairHeader" sx={{ p: 2, pt: { xs: 5, sm: 20, md: 20 }, mt: 0, fontSize: 23, textShadow: '8 8 6 #000', color: '#FFFF' }}>
            <h1> Bumper Repair</h1>
            <p>
              Urgent Care Bumper Repair’s expertise is in restoring your damaged bumper to as it was new.
              If necessary, we can replace your parts whether they require paint to match the vehicle or a part that does not require any paint.
              If your new part does require paint, we have the ability to collect a color sample and color code along with the deposit for the part.
              Once painted, we will bring it to you or you can come to us for installation which takes one to two hours.
              Which gives you the ability to use your vehile while the part is being painted. No need to leave your vehicle at a shop for any reason (NO RENTAL CAR NEEDED).

            </p>
            <p></p>

            <Button className="btn-service" sx={{ pb: 0, fontSize: 20 }}>
              Get A Free Estimate
            </Button>
            <br />
            <Button className="btn-service" sx={{ pb: 0, fontSize: 20 }} onClick={()=>scrollToView()}>
              View Our Gallery
            </Button>
          </Grid>
        </Stack>
        <Stack sx={{ p:4, backgroundColor: '#333', textAlign: 'center' }}>
        <Typography id={"serviceRef"}  sx={{borderLeft:'dotted 1px #fff', borderRight:'dotted 1px #fff', color:'#fff', p:0}}>Our Work</Typography>
        </Stack>
        <Stack sx={{ p: 0, backgroundImage:'linear-gradient(rgba(238, 238, 238, 0.925), rgba(238, 238, 238, 0.925)),url(/../assets/images/home/background.jpg)',backgroundSize:'cover', height:{xs:300,sm:660,md:660}, textAlign: 'center' }}>
          <Swiper
            effect={"coverflow"}
            init={true}
            loop={false}
            grabCursor={true}
            centeredSlides={true}
            navigation={true}
            slidesPerView={"auto"}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 0,
              modifier: 3,
              slideShadows: true,
            }}
            pagination={{ dynamicBullets: true,}}
            modules={[EffectCoverflow, Pagination, Navigation]}
            className="bumperrepair-swiper"
          >
            <SwiperSlide >
              <img src="assets/images/M4/069.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/070.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/071.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/072.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/073.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/074.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/075.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/076.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/077.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/078.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/079.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/M4/080.jpg" className="captionImages" alt="..." />
            </SwiperSlide>
            <SwiperSlide>
          
              <Box className="get-free-estimate"  sx={{mt:-6,height:800, backgroundImage:'linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),url(assets/images/M4/081.jpg)'}}>
              <Typography component="h1" sx={{color:'#fff',textShadow:'4px 4px 5px #000;', position:'relative', top:{xs:50,sm:100}, fontSize:{xs:20, sm:32}}}><h1>Urgent Care Bumper Repair</h1></Typography>
              <Link  
                       component = {NavLink}
                       to={'/estimate'}
                       key={'/estimate'}
                       href="" sx={{fontSize:{xs:20, sm:32}, top:{xs:25, sm:100}, position:'relative'}}
                       className="btn-service">
                  Get A Free Estimate
                </Link>
              </Box>
            </SwiperSlide>
          </Swiper>
        </Stack>
        <Stack sx={{ p: 0, backgroundColor: '#f9fcff', textAlign: 'center' }}>
          <Box sx={{ pt: 0, pb: 2, display: 'flex', justifyContent: "center" }}><img className="logoSection" src="assets/images/logo2.png" alt="wrapkit" /></Box>
        </Stack>
        <Stack sx={{ p: 0, backgroundImage:'linear-gradient(rgba(238, 238, 238, 0.925), rgba(238, 238, 238, 0.925)),url(/../assets/images/home/background.jpg)',backgroundSize:'cover', height:{xs:300,sm:660,md:660}, textAlign: 'center' }}>
          <Swiper
            effect={"coverflow"}
            init={true}
            loop={false}
            grabCursor={true}
            centeredSlides={true}
            navigation={true}
            slidesPerView={"auto"}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 0,
              modifier: 3,
              slideShadows: true,
              
            }}
            pagination={{ dynamicBullets: true,}}
            modules={[EffectCoverflow, Pagination, Navigation]}
            className="bumperrepair-swiper"
          >
            <SwiperSlide>
              <img src="assets/images/Car1/082.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/083.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/084.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/085.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/086.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/087.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/088.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/089.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/090.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/091.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/092.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/093.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/094.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/095.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/096.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Car1/097.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <Box className="get-free-estimate"  sx={{mt:-6,height:800, backgroundImage:'linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),url(assets/images/Car1/098.jpg)'}}>
              <Typography component="h1" sx={{color:'#fff',textShadow:'4px 4px 5px #000;', position:'relative', top:{xs:50,sm:100}, fontSize:{xs:20, sm:32}}}><h1>Urgent Care Bumper Repair</h1></Typography>
              <Link  
                       component = {NavLink}
                       to={'/estimate'}
                       key={'/estimate'}
                       href="" sx={{fontSize:{xs:20, sm:32}, top:{xs:25, sm:100}, position:'relative'}}
                       className="btn-service">
                  Get A Free Estimate
                </Link>
              </Box>
            </SwiperSlide>
          </Swiper>
        </Stack>
        <Stack sx={{ p: 0, backgroundColor: '#f9fcff', textAlign: 'center' }}>
          <Box sx={{ pt: 0, pb: 2, display: 'flex', justifyContent: "center" }}><img className="logoSection" src="assets/images/logo2.png" alt="wrapkit" /></Box>
        </Stack>
        <Stack sx={{ p: 0, backgroundImage:'linear-gradient(rgba(238, 238, 238, 0.925), rgba(238, 238, 238, 0.925)),url(/../assets/images/home/background.jpg)',backgroundSize:'cover', height:{xs:300,sm:660,md:660}, textAlign: 'center' }}>
          <Swiper
            effect={"coverflow"}
            init={true}
            loop={false}
            grabCursor={true}
            centeredSlides={true}
            navigation={true}
            slidesPerView={"auto"}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 0,
              modifier: 3,
              slideShadows: true,
            }}
            pagination={{ dynamicBullets: true,}}
            modules={[EffectCoverflow, Pagination, Navigation]}
            className="bumperrepair-swiper"
          >
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_1.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_2.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_3.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_4.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_5.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_6.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_7.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_8.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_9.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_10.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_11.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_12.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_13.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_14.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_15.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_16.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_17.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_18.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_19.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_20.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_21.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_22.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_23.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_24.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_25.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_26.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_27.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_28.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/Aptera/IMG_29.jpg"   className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
            <Box className="get-free-estimate"  sx={{mt:-6,height:670, backgroundImage:'linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),url(assets/images/Aptera/IMG_29.jpg)'}}>
            <Typography component="h1" sx={{color:'#fff',textShadow:'4px 4px 5px #000;', position:'relative', top:{xs:50,sm:100}, fontSize:{xs:20, sm:32}}}><h1>Urgent Care Bumper Repair</h1></Typography>
            <Link  
                       component = {NavLink}
                       to={'/estimate'}
                       key={'/estimate'}
                       href="" sx={{fontSize:{xs:20, sm:32}, top:{xs:25, sm:100}, position:'relative'}}
                       className="btn-service">
                  Get A Free Estimate
                </Link>
              </Box>
            </SwiperSlide>
          </Swiper>
        </Stack>
        <Stack sx={{ p: 0, backgroundColor: '#f9fcff', textAlign: 'center' }}>
          <Box sx={{ pt: 0, pb: 2, display: 'flex', justifyContent: "center" }}><img className="logoSection" src="assets/images/logo2.png" alt="wrapkit" /></Box>
        </Stack>
        <Stack sx={{ p: 0, backgroundImage:'linear-gradient(rgba(238, 238, 238, 0.925), rgba(238, 238, 238, 0.925)),url(/../assets/images/home/background.jpg)',backgroundSize:'cover', height:{xs:300,sm:660,md:660}, textAlign: 'center' }}>
          <Swiper
            effect={"coverflow"}
            init={true}
            loop={false}
            grabCursor={true}
            centeredSlides={true}
            navigation={true}
            slidesPerView={"auto"}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 0,
              modifier: 3,
              slideShadows: true,
            }}
            pagination={{ dynamicBullets: true,}}
            modules={[EffectCoverflow, Pagination, Navigation]}
            className="bumperrepair-swiper"
          >
            <SwiperSlide>
              <img src="assets/images/porsche/150.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
            <img src="assets/images/porsche/151.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
            <img src="assets/images/porsche/152.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
            <img src="assets/images/porsche/153.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
            <img src="assets/images/porsche/154.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
            <img src="assets/images/porsche/155.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <Box className="get-free-estimate"  sx={{mt:-6,height:800, backgroundImage:'linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),url(assets/images/porsche/155.jpg)'}}>
              <Typography component="h1" sx={{color:'#fff',textShadow:'4px 4px 5px #000;', position:'relative', top:{xs:50,sm:100}, fontSize:{xs:20, sm:32}}}><h1>Urgent Care Bumper Repair</h1></Typography>
              <Link  
                       component = {NavLink}
                       to={'/estimate'}
                       key={'/estimate'}
                       href="" sx={{fontSize:{xs:20, sm:32}, top:{xs:25, sm:100}, position:'relative'}}
                       className="btn-service">
                  Get A Free Estimate
                </Link>
              </Box>
            </SwiperSlide>
          </Swiper>
        </Stack>
        <Stack sx={{ p: 0, backgroundColor: '#f9fcff', textAlign: 'center' }}>
          <Box sx={{ pt: 0, pb: 2, display: 'flex', justifyContent: "center" }}><img className="logoSection" src="assets/images/logo2.png" alt="wrapkit" /></Box>
        </Stack>
        <Stack sx={{ p: 0, backgroundImage:'linear-gradient(rgba(238, 238, 238, 0.925), rgba(238, 238, 238, 0.925)),url(/../assets/images/home/background.jpg)',backgroundSize:'cover', height:{xs:300,sm:660,md:660}, textAlign: 'center' }}>
          <Swiper
            effect={"coverflow"}
            init={true}
            loop={false}
            grabCursor={true}
            centeredSlides={true}
            navigation={true}
            slidesPerView={"auto"}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 0,
              modifier: 3,
              slideShadows: true,
            }}
            pagination={{ dynamicBullets: true,}}
            modules={[EffectCoverflow, Pagination, Navigation]}
            className="bumperrepair-swiper"
          >
            <SwiperSlide>
              <img src="assets/images/suv/1.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/suv/2.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <img src="assets/images/suv/3.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/4.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/5.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/6.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/7.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/8.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/9.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/10.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/11.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
             <img src="assets/images/suv/12.jpg"  className="captionImages" alt="..."/>
            </SwiperSlide>
            <SwiperSlide>
              <Box className="get-free-estimate"  sx={{mt:-6,height:800, backgroundImage:'linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),url(assets/images/suv/12.jpg)'}}>
                <Typography component="h1" sx={{color:'#fff',textShadow:'4px 4px 5px #000;', position:'relative', top:{xs:50,sm:100}, fontSize:{xs:20, sm:32}}}><h1>Urgent Care Bumper Repair</h1></Typography>
                <Link  
                       component = {NavLink}
                       to={'/estimate'}
                       key={'/estimate'}
                       href="" sx={{fontSize:{xs:20, sm:32}, top:{xs:25, sm:100}, position:'relative'}}
                       className="btn-service">
                  Get A Free Estimate
                </Link>
              </Box>
            </SwiperSlide>
          </Swiper>
        </Stack>
        <Stack sx={{ p: 0, backgroundColor: '#333', textAlign: 'center' }}>
          <Box sx={{ pt: 0, pb: 2, display: 'flex', justifyContent: "center" }}>
            <Link 
             component = {NavLink}
             to={'/service'}
             key={'/service'}
            href="" 
            className="bumperrepair-redirect-btn" >
              Return To Services
            </Link>
          </Box>
        </Stack>
      </Stack>

    </>
  );
}
